---
site:
  title: "Zero Touch Platform Training Template"
  url: https://demo.redhat.com/zero-touch-training
  start_page: modules::zero-touch-platform-training.adoc

content:
  sources:
    - url: ./
      start_path: content
ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
