---
# By default egress traffic is not allowed, define below the ports allowed.
egress:
  - ports:
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 3000
ingress:
  - ports:
      - protocol: TCP
        port: 3000