---
# By default egress traffic is not allowed, define below the ports allowed.
egress:
  - ports:
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 8443
      - protocol: TCP
        port: 3000
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 22

ingress:
  - ports:
      - protocol: TCP
        port: 3000
      - protocol: TCP
        port: 8443