---
containers:
  - name: "vscode"
    image: "codercom/code-server:latest"
    memory: "4G"
    cpu: "1"
    ports:
      - name: vscode
        containerPort: 8080
        protocol: TCP
    environment:
      PASSWORD: {{ common_password }}
      SUDO_PASSWORD: {{ common_password }}
      GIT_REPO: "https://github.com/rhpds/zero_touch_template_wilson.git"
      DEFAULT_WORKSPACE: "/home/coder/workspace/zero_touch_template_wilson"
    commands:
      - "mkdir -p /home/coder/workspace"
      - "cd /home/coder/workspace && git clone https://github.com/rhpds/zero_touch_template_wilson.git"
      - "cd /home/coder/workspace/zero_touch_template_wilson && git checkout -b lab-development"
      - "git config --global user.name 'Lab Developer'"
      - "git config --global user.email 'developer@lab.local'"
      - "chown -R coder:coder /home/coder/workspace"
    services:
      - name: vscode
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: vscode
    routes:
      - name: vscode
        host: vscode
        service: vscode
        targetPort: 8080
        tls: true
virtualmachines:
  - name: "lab-server"
    image: "rhel-9.6"
    memory: "4G"
    cores: 2
    packages:
      - git
      - vim
      - tree
      - htop
      - tmux
      - curl
      - wget
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
    networks:
      - default
