---
containers:
  - name: "vscode"
    image: "linuxserver/code-server:latest"
    memory: "4G"
    cpu: "1"
    ports:
      - name: vscode
        containerPort: 8443
        protocol: TCP
    environment:
      PUID: "1001"
      PGID: "1001"
      PASSWORD: "{{ common_password }}"
      SUDO_PASSWORD: "{{ common_password }}"
      DEFAULT_WORKSPACE: "/config/workspace/zero_touch_template_wilson"
    commands:
      - "mkdir -p /config/workspace"
      - "cd /config/workspace && git clone https://github.com/rhpds/zero_touch_template_wilson.git"
      - "cd /config/workspace/zero_touch_template_wilson && git checkout -b lab-development"
      - "git config --global user.name 'Lab Developer'"
      - "git config --global user.email 'developer@lab.local'"
      - "chown -R abc:abc /config/workspace"
    services:
      - name: vscode
        ports:
          - port: 8443
            protocol: TCP
            targetPort: 8443
            name: vscode
    routes:
      - name: vscode
        host: vscode
        service: vscode
        targetPort: 8443
        tls: true
virtualmachines:
  - name: "lab-server"
    image: "rhel-9.6"
    memory: "4G"
    cores: 2
    packages:
      - git
      - vim
      - tree
      - htop
      - tmux
      - curl
      - wget
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
    networks:
      - default
