---
containers:
  - name: "vscode"
    image: "registry.redhat.io/ubi9/ubi:latest"
    memory: "4G"
    cpu: "1"
    ports:
      - name: vscode
        containerPort: 8080
        protocol: TCP
    environment:
      PASSWORD: "{{ common_password }}"
    volumes:
      - name: workspace-data
        emptyDir: {}
      - name: vscode-config
        emptyDir: {}
    volumeMounts:
      - name: workspace-data
        mountPath: /opt/app-root/src/workspace
      - name: vscode-config
        mountPath: /opt/app-root/src/.local
    commands:
      - "dnf install -y nodejs npm git curl"
      - "npm install -g @coder/code-server"
      - "useradd -u 1001 -g 0 -m coder"
      - "mkdir -p /opt/app-root/src/workspace"
      - "mkdir -p /opt/app-root/src/.local/share/code-server"
      - "chown -R coder:root /opt/app-root/src"
      - "cd /opt/app-root/src/workspace && git clone https://github.com/rhpds/zero_touch_template_wilson.git"
      - "cd /opt/app-root/src/workspace/zero_touch_template_wilson && git checkout -b lab-development"
      - "git config --global user.name 'Lab Developer'"
      - "git config --global user.email 'developer@lab.local'"
      - "su - coder -c 'nohup code-server --bind-addr 0.0.0.0:8080 --password \"$PASSWORD\" --disable-telemetry --user-data-dir /opt/app-root/src/.local/share/code-server /opt/app-root/src/workspace/zero_touch_template_wilson > /tmp/code-server.log 2>&1 &'"
      - "sleep 5"
    services:
      - name: vscode
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: vscode
    routes:
      - name: vscode
        host: vscode
        service: vscode
        targetPort: 8080
        tls: true
virtualmachines:
  - name: "lab-server"
    image: "rhel-9.6"
    memory: "4G"
    cores: 2
    packages:
      - git
      - vim
      - tree
      - htop
      - tmux
      - curl
      - wget
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
    networks:
      - default
